name = "auth-backend"
main = "src/worker.js"
compatibility_date = "2024-09-23"

[vars]
COOKIE_NAME = "auth_token"
JWT_SECRET  = "apage-auth-secret-2024-rishabh-xyz-abc-123"
RESEND_API_KEY  = "re_52sMi8aL_F6x6EynDVdTw1n6DLBuW3W6h"

[[d1_databases]]
binding       = "DB"
database_name = "auth_db"
database_id   = "local-db"
